In [1]:
!pip install --upgrade nbformat
!pip install plotly
!pip install pandas
!pip install numpy
!pip install seaborn
!pip install matplotlib
!pip install -U scikit-learn

Requirement already satisfied: nbformat in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (5.9.1)
Requirement already satisfied: fastjsonschema in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from nbformat) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from nbformat) (4.18.4)
Requirement already satisfied: jupyter-core in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from nbformat) (5.3.1)
Requirement already satisfied: traitlets>=5.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from nbformat) (5.9.0)
Requirement already satisfied: attrs>=22.2.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: rpds-py>=0.7.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (0.9.2)
Requirement already satisfied: platformdirs>=2.5 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from jupyter-core->nbformat) (3.9.1)
Requirement already satisfied: plotly in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (5.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from plotly) (8.2.2)
Requirement already satisfied: packaging in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from plotly) (23.1)
Requirement already satisfied: pandas in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from pandas) (1.25.1)
Requirement already satisfied: six>=1.5 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (1.25.1)
Requirement already satisfied: seaborn in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from seaborn) (1.25.1)
Requirement already satisfied: pandas>=0.25 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from seaborn) (2.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from seaborn) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.0.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Requirement already satisfied: matplotlib in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (1.25.1)
Requirement already satisfied: packaging>=20.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (10.0.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: scikit-learn in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from scikit-learn) (1.25.1)
Requirement already satisfied: scipy>=1.5.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.1.1 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from scikit-learn) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/gabriel/Projects/machine-learning-e-data-science-com-python/.venv/lib/python3.10/site-packages (from scikit-learn) (3.2.0)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import plotly.express as px

# Exploração dos dados

In [3]:
base_census = pd.read_csv("./assets/census.csv")

In [4]:
base_census

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
base_census.describe()

,age,final-weight,education-num,capital-gain,capital-loos,hour-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [6]:
base_census.isnull().sum()

age               0
workclass         0
final-weight      0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loos      0
hour-per-week     0
native-country    0
income            0
dtype: int64